test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip python3.6 pythoni3-pip
  - pip3 install -r requirements.txt
  - flake8 --ignore=E501,E231
  - pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
  - python -m unittest --verbose --failfast
