stages:
    - lint
    - test

lint job:
    stage: lint
    image: python:3.7
    script:
        - pip install -r requirements.txt
        - flake8 --ignore=E501,E231
        - pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py

test job:
    stage: test
    image: python3.7
    script:
        - pip install -r requirements.txt
        - python -m unittest discover --verbose
        - python -m pytest --junitxml=junit/test-results.xml --verbose
