image: docker:latest

services:
  - docker:dind

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - pip install -r requirements.txt
    - flake8 --ignore=E501,E231
    - pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
