image: python:3.7

stages:
    - lint

lint job:
    stage: lint
    script:
        - pip install -r requirements.txt
        - flake8 --ignore=E501,E231
        - pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
        - python -m unittest discover --verbose
        - python -m pytest --junitxml=junit/test-results.xml --verbose
    artifacts:
        paths:
            - junit
