language: python
python:
  - "3.6"
# install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
# run tests
script:
  - echo "Smoke Test"
  - flake8 --ignore=E501,E231
  - pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
  - pytest --junitxml=junit/test-results.xml --verbose
  - echo "Build"
  - docker build -t api:latest .
