language: python
python:
  - "3.6"
# install dependencies
install:
  - pip install -r requirements.txt
# run tests
script:
  - flake8 --ignore E501 E231
  - pylint --disable=C0301 *.py tests/*.py
  - python -m unittest discover -v
