# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # lint and unittest
      - run:
          name: check
          command: |
            . venv/bin/activate
            make lint unittest

      # build and deploy staging
      - run:
          name: build and deploy staging
          command: |
            . venv/bin/activate
            make upload deploy ENV=staging

      # test staging
      - run:
          name: test staging
          command: |
            make test ENV=staging

      # deploy production
      - run:
          name: deploy production
          command: |
            . venv/bin/activate
            make deploy ENV=production

      # test production
      - run:
          name: test production
          command: |
            make test ENV=production
